### ISSUE TITLE
Multiple zip file upload

### ISSUE THREAD

**Issue by dakriy** [wwu-cs/Submitty#100]
Allow for multiple zip files to be uploaded at once

**Comment by CalebJ2** [comment]
If we allow the user to specify the library name I don't think this is worth it. Would be a pain to let users set names on multiple files.

**Comment by dakriy** [comment]
What do you mean? I'm just talking about uploading multiple zip files at once. The library name is based upon the name of the zip file uploaded.

**Comment by CalebJ2** [comment]
In class he mentioned the possibility of adding another field on the form to let the admin set a different name/description when uploading. I was thinking about how that would be done with multiple files. I doubt that feature will get added so multiple zip files sounds nice. Idk

**Comment by CalebJ2** [comment]
Not doing this. One at a time is preferred when allowing the user to set library name.
