### ISSUE TITLE
Fix Queries for the TeamView.php

### ISSUE THREAD

**Issue by prestoncarman** [wwu-cs/Submitty#11]
**Describe the bug**
Should not execute queries in the view.

```
app/views/submission/TeamView.php:  $members[] = $this->core->getQueries()->getUserById($teammate);
app/views/submission/TeamView.php:  $seekers[] = $this->core->getQueries()->getUserById($user_seeking_team);
```

**Expected behavior**
The expected behavior is to execute the queries in the controller and pass the result to the view.

**Comment by CalebJ2** [comment]
See pull request #17
