### ISSUE TITLE
[gradeable] Add button linking to Homework Library search page

### ISSUE THREAD

**Issue by prestoncarman** [wwu-cs/Submitty#25]
**What problem are you trying to solve with Submitty**
The initial link to get the Homework Library search page.

**Describe the way you'd like to solve this problem**
Similar to the upload gradeable link that currently is shown in the create gradeable process.

**Comment by PlasmaIntec** [comment]
See https://github.com/wwu-cs/Submitty/pull/48

**Comment by dakriy** [comment]
Closing as the related PR has been merged!
