### ISSUE TITLE
[library] Add button to library admin page.

### ISSUE THREAD

**Issue by prestoncarman** [wwu-cs/Submitty#27]
**What problem are you trying to solve with Submitty**
Create a link similar to create course on the homepage that links to a page with multiple tabs (gold, rose, silver). The link should be only visible for instructors or admins.

**Describe the way you'd like to solve this problem**
The page with the tabs should only be stubbed out with example text (https://www.lipsum.com/)

**Comment by dakriy** [comment]
I think this has been done as it is marked as completed and the related PR seems to have been merged.
