### ISSUE TITLE
Fix Queries for the LateDayView.php

### ISSUE THREAD

**Issue by prestoncarman** [wwu-cs/Submitty#3]
**Describe the bug**
Should not execute queries in the view.

```
app/views/admin/LateDayView.php:  $students = $this->core->getQueries()->getAllUsers();
```

**Expected behavior**
The expected behavior is to execute the queries in the controller and pass the result to the view.

**Comment by dakriy** [comment]
Merged so closing.

**Comment by dakriy** [comment]
Gotta make tests
