### ISSUE TITLE
[library] import gradeables into library

### ISSUE THREAD

**Issue by prestoncarman** [wwu-cs/Submitty#30]
**What problem are you trying to solve with Submitty**
Create a twig file with an HTML form for adding gradeables to the library. Consider importing gradeables located on the local file system.

**Describe the way you'd like to solve this problem**
This is only the HTML form with dummy text (https://www.lipsum.com/).

**Comment by lucasmarcondes** [comment]
Clarification this issue _only_ consists of creating a form for submitting gradeables, whether it be an upload feature and/or some sort of GitHub folder sync. This page will eventually be one of the tabs in the issue for #27

**Comment by lucasmarcondes** [comment]
This issue has been split into three tasks that will be connected to #27 via 3 separate tabs:
- #71, #72 | Upload Tab
- #69 | Local File System Upload Tab
- #67 | Github Synchronization Tab
