### ISSUE TITLE
[library] config file option to enable homework library

### ISSUE THREAD

**Issue by prestoncarman** [wwu-cs/Submitty#31]
**What problem are you trying to solve with Submitty**
Review the submitty config file and add an option to enable the homework library. 

**Describe the way you'd like to solve this problem**
As we develop the homework library, this option will allow us to disable it and commit it back to the project. Then when the project is done, the default can change to be enabled.

**Comment by dakriy** [comment]
Checkout #59 for progress

**Comment by dakriy** [comment]
Welp, it's been merged, so I am closing this issue.
