### ISSUE TITLE
Implement local file system actions for library form

### ISSUE THREAD

**Issue by CalebJ2** [wwu-cs/Submitty#69]
Implement back end for #66. 

Copy imported library files to the correct places from the local file system

---

- [ ] #90 Return all config.json file paths

**Comment by stephenermshar** [comment]
It looks the important code for this is the `handleUploadCourseMaterials` function in `site/public/js/drag-and-drop.js` and the `ajaxUploadSubmission` function in `site/app/controllers/student/SubmissionController.php`. These handle file upload for gradeable submissions and might need to be generalized to handle uploads for the homework library as well.

**Comment by stephenermshar** [comment]
related to #81

**Comment by stephenermshar** [comment]
https://github.com/Submitty/Tutorial is an example of a library that would be uploaded by the admin.

**Comment by dakriy** [comment]
I think this has been done with #72 (under review) as well as #81 (completed) with the frontend being done with #71. So closing this.
