### ISSUE TITLE
Fix Queries for the HomePageView.php

### ISSUE THREAD

**Issue by prestoncarman** [wwu-cs/Submitty#7]
**Describe the bug**
Should not execute queries in the view.

```
app/views/HomePageView.php:  $rank = $this->core->getQueries()->getGroupForUserInClass($course['semester'], $course['title'], $user->getId());
```

**Expected behavior**
The expected behavior is to execute the queries in the controller and pass the result to the view.

**Comment by PlasmaIntec** [comment]
Fixed by [7a2b920](https://github.com/wwu-cs/Submitty/commit/7a2b920a0ed19bd23ae6e2311176ed544760f2a7)
