### ISSUE TITLE
Move showLibrary into its own Controller

### ISSUE THREAD

**Issue by PlasmaIntec** [wwu-cs/Submitty#78]
Currently, `showLibrary` and `showLibraryManager` are piggybacking off of `HomePageController.php`.
There is also a copy of `showLibrary` in UsersController to get dynamic routes to work.

We should separate these into their own Controller class, preferably `HomeworkLibraryController.php`, and consolidate the showLibrary functions.

**Comment by CalebJ2** [comment]
Updated the description with more things to move.
I tried to add a controller like this but the routes I defined weren't being seen or run or something. Maybe controllers have to be included somewhere?
