### ISSUE TITLE
[library] Create endpoint route for uploading gradeables for the library

### ISSUE THREAD

**Issue by dakriy** [wwu-cs/Submitty#88]
Enable uploading of zip files. The endpoint should unzip the gradeables and create a group from it and plop it into the submitty folder.

**Comment by sballance** [comment]
@dakriy is this issue a duplicate of #72? I'm not sure what the difference is.

**Comment by sballance** [comment]
We'll need to make sure that only admins have access to the post request.

**Comment by dakriy** [comment]
@sballance Yeah it probably is. We'll just use that one.
